# Generated by Django 5.0 on 2023-12-06 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_audio_file_message_image_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='audio_file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='image_file',
        ),
        migrations.RemoveField(
            model_name='message',
            name='video_file',
        ),
    ]
