# Generated by Django 5.0 on 2023-12-06 19:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_message_audio_file_remove_message_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstatus',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
